name: Team-Workflow

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Primer-Trabajo:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setear JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Running Tests
        run: |
          mvn clean install
          mvn test
          
